# Generated by Django 3.2.8 on 2023-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(blank=True, default='default pp/man-303792_1280.png', null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
