# Generated by Django 4.2 on 2024-10-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LitingImage',
            new_name='ListingImage',
        ),
    ]
