# Generated by Django 3.2.8 on 2023-10-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zoipcode',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='listing',
            name='sqrft',
            field=models.IntegerField(default=0),
        ),
    ]
